{% set version = "0.19.0" %}

{% set variant = "openblas" %}


package:
  name: scipy
  version: {{ version }}

source:
  fn: scipy-{{ version }}.tar.gz
  url: https://github.com/scipy/scipy/archive/v{{ version }}.tar.gz
  sha256: efa71d68ef0fa4a2836a3058fc1c5aa6b61d93ee0248a127cd862ea3bf22b69a
  patches:
    #
    # Fix a test failure caused by a change to NumPy's `assert_equal`'s.
    #
    # xref: https://github.com/scipy/scipy/pull/7229
    #
    - PR_7229.diff

build:
  number: 201
  # We lack openblas on Windows, and therefore can't build scipy there either currently.
  skip: true  # [win or (np!=113 and linux)]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - gcc          # [osx]
    - python
    - setuptools
    - cython
    - blas 1.1 {{ variant }}
    - libgfortran  # [linux]
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
  run:
    - python
    - blas 1.1 {{ variant }}
    - libgfortran
    - openblas 0.2.19|0.2.19.*
    - numpy x.x

test:
  requires:
    - nose
    - mpmath

about:
  home: http://www.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - rgommers
    - ocefpaf
