{% set version = "1.10.1" %}

package:
  name: scipy
  version: {{ version }}

# use 'python_impl' in meta.yaml so it gets picked up by rendering
# [python_impl == "pypy"]

source:
  # The sdist distributed by scipy contains pre-compiled pythran sources,
  # as well as the relevant submodules; by taking the tarball from github
  # we can compile pythran ourselves (or not), but manually need to include
  # the submodules (not in tarball due to dear-github/dear-github#214)
  - url: https://github.com/scipy/scipy/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8f08e1742c9b09eb58640fa5a56031d6e1844806899e883fbe7447ca86fe8c55
    patches:
      # backport https://github.com/scipy/scipy/pull/18006
      - patches/0001-BLD-use-a-relative-path-to-numpy-pybind11-pythran-in.patch
      # backport https://github.com/scipy/scipy/pull/18034
      - patches/0002-BLD-avoid-running-run_command-py3-.-for-better-cross.patch
      # backport https://github.com/scipy/scipy/pull/18263
      - patches/0003-BUG-some-tweaks-to-PROPACK-f2py-wrapper-and-build-fl.patch  # [not win]
      # backport https://github.com/scipy/scipy/pull/18264 (3 commits)
      - patches/0004-MAINT-remove-from-numpy.math-cimport-usages.patch           # [not win]
      - patches/0005-MAINT-sync-changes-to-npy_blas.h-and-npy_blas_base.h.patch  # [not win]
      - patches/0006-BUG-include-npy_common.h-in-npy_cblas.h.patch               # [not win]
      # backport https://github.com/scipy/scipy/pull/18426
      - patches/0007-BLD-fix-two-regressions-for-Duse-g77-abi.patch              # [not win]
  # https://github.com/scipy/scipy/tree/v{{ version }}/scipy/_lib
  - git_url: https://github.com/scipy/boost-headers-only.git
    git_rev: 3af99e6d566043072e95bc882d32c9c26f37e0ba
    folder: scipy/_lib/boost
  - git_url: https://github.com/scipy/highs.git
    git_rev: 4a122958a82e67e725d08153e099efe4dad099a2
    folder: scipy/_lib/highs
  - git_url: https://github.com/scipy/unuran.git
    git_rev: a63d39160e5ecc4402e7ed0e8417f4c3ff9634cb
    folder: scipy/_lib/unuran
  # https://github.com/scipy/scipy/tree/v{{ version }}/scipy/sparse/linalg/_propack
  - git_url: https://github.com/scipy/PROPACK.git
    git_rev: cc32f3ba6cf941e4f9f96d96e2fc5762ea0c1014
    folder: scipy/sparse/linalg/_propack/PROPACK

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - cmake                                  # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # pythran code needs clang-cl on windows
    - clang                                  # [win]
    - {{ compiler('fortran') }}              # [unix]
    # WARNING: It's not recommended to use these MinGW compilers with python extensions
    # numpy.distutils has a complex mechanism to facilitate mixing gfortran and MSVC
    # https://pav.iki.fi/blog/2017-10-08/pywingfortran.html#building-python-wheels-with-fortran-for-windows
    - {{ compiler('m2w64_fortran') }}        # [win]
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - setuptools <60  # [win]
    - cython
    - meson-python    # [unix]
    - ninja           # [unix]
    - pkg-config      # [unix]
    - python-build    # [unix]
    - pybind11
    - pythran
    - numpy
    - pip
  run:
    - python
    # see np_maxversion in https://github.com/scipy/scipy/blob/v{{ version }}/setup.py
    - {{ pin_compatible('numpy', upper_bound='1.27') }}
    # needed for scipy.datasets
    - pooch

{% set tests_to_skip = "_not_a_real_test" %}
# on the slowest agents, these tests take more than 20min in emulation
{% set tests_to_skip = tests_to_skip + " or (test_lsq_linear and test_large_rank_deficient)" %}   # [aarch64 or ppc64le]
{% set tests_to_skip = tests_to_skip + " or (test_iterative and test_precond_inverse[case1])" %}  # [aarch64 or ppc64le]
{% set tests_to_skip = tests_to_skip + " or (test_optimize and TestBrute and test_workers)" %}    # [aarch64 or ppc64le]
# tests that run into timeouts (set in scipy test suite) in emulation
{% set tests_to_skip = tests_to_skip + " or (test_propack and test_examples)" %}                  # [aarch64 or ppc64le]
# occasionally runs out of memory on windows + pypy
{% set tests_to_skip = tests_to_skip + " or test_bootstrap_against_" %}                           # [(python_impl == "pypy") and win]
# very slow tests for pypy in emulation
{% set tests_to_skip = tests_to_skip + " or TestDualAnnealing or TestQuad or TestNQuad" %}        # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or TestDifferentialEvolutionSolver or TestTRF" %}        # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or TestMonteCarloHypothesisTest" %}                      # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or (TestBessel and test_fs_param)" %}                    # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or (TestOrdQZWorkspaceSize and test_decompose)" %}       # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_all_nograd_minimizers or test_basic_fit_mle" %}  # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_cdf_against_tables or test_pdf_integration" %}   # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_cdist_ and (refcount or calling_convention)" %}  # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_conditionally_positive_definite" %}              # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_cont_basic[500 or test_cython_api[elliprj]" %}   # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_filtfilt_gust or test_kappa3_array_gh13582" %}   # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_fitstart[genexpon-shapes28] or test_gh12922" %}  # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_integration_sparse or test_kdtree_box" %}        # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_minimize_callback_copies_array[fmin]" %}         # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_mip1 or test_mixed_threads_processes" %}         # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_modules_importable or test_neldermead_limit" %}  # [(python_impl == "pypy") and (aarch64 or ppc64le)]
{% set tests_to_skip = tests_to_skip + " or test_random_exact or test_random_complex_exact" %}    # [(python_impl == "pypy") and (aarch64 or ppc64le)]

test:
  requires:
    - pytest
    - pytest-timeout
    - pytest-xdist
    - mpmath
    # make sure we test with all blas implementations
    - libblas =*=*{{ blas_impl }}
  commands:
    # show SIMD features (some failures occur depending on presence/absence of e.g. AVX512)
    - python -c "import numpy; numpy.show_config()"
    - python -c "import sys; import numpy; sys.exit(0 if 'AVX512F? AVX512CD?' in numpy.lib.utils._opt_info() else 1)"  # [enforce_avx512 == "absent" and blas_impl in ("mkl", "openblas")]
    - python -c "import sys; import numpy; sys.exit(0 if 'AVX512F* AVX512CD*' in numpy.lib.utils._opt_info() else 1)"  # [enforce_avx512 == "present" and blas_impl in ("mkl", "openblas")]
    # the tests ppc64le and aarch64 are currently run through emulation in QEMU;
    # since this takes much longer, do not run the most heavy-weight tests, i.e. use
    # label='fast'; same for PyPy due to huge runtime; otherwise set label='full'
    {% set label = "'fast'" if (aarch64 or ppc64le or python_impl == "pypy") else "'full'" %}
    # for signature of scipy.test see below (note default: label='fast'):
    # https://github.com/scipy/scipy/blob/v1.7.0/scipy/_lib/_testutils.py#L27
    {% set param = "verbose=1, label=" + label + ", tests=None" %}
    {% set extra = "extra_argv=['-k', 'not (" + tests_to_skip + ")', '-nauto', '--timeout=1200', '--durations=50']" %}
    - python -c "import scipy, sys; sys.exit(not scipy.test({{ param }}, {{ extra }}))"
  imports:
    - scipy
    # reference for public API is effectively
    # https://github.com/scipy/scipy/blob/main/scipy/_lib/tests/test_public_api.py
    - scipy.cluster
    - scipy.cluster.hierarchy
    - scipy.cluster.vq
    - scipy.constants
    - scipy.datasets
    - scipy.fft
    - scipy.fftpack
    - scipy.integrate
    - scipy.interpolate
    - scipy.io
    - scipy.io.arff
    - scipy.io.matlab
    - scipy.io.wavfile
    - scipy.linalg
    - scipy.linalg.blas
    - scipy.linalg.cython_blas
    - scipy.linalg.cython_lapack
    - scipy.linalg.interpolative
    - scipy.linalg.lapack
    - scipy.misc
    - scipy.ndimage
    - scipy.odr
    - scipy.optimize
    - scipy.signal
    - scipy.signal.windows
    - scipy.sparse
    - scipy.sparse.csgraph
    - scipy.sparse.linalg
    - scipy.spatial
    - scipy.spatial.distance
    - scipy.spatial.transform
    - scipy.special
    - scipy.stats
    - scipy.stats.contingency
    - scipy.stats.distributions
    - scipy.stats.mstats
    - scipy.stats.qmc
    - scipy.stats.sampling

about:
  home: http://www.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - rgommers
    - ocefpaf
    - h-vetinari
