{% set version = "1.6.3" %}

package:
  name: scipy
  version: {{ version }}

source:
  url: https://github.com/scipy/scipy/archive/v{{ version }}.tar.gz
  sha256: 6cdb9d3aabe46c1602d9fd2f34812700068eddfe3ffd1dafcbd7e7960a874e1c

build:
  number: 0
  skip: true  # [py2k or py<=36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('fortran') }}   # [unix]
    # WARNING: It's not recommended to use these MinGW compilers with python extensions
    # numpy.distutils has a complex mechanism to facilitate mixing gfortran and MSVC
    # https://pav.iki.fi/blog/2017-10-08/pywingfortran.html#building-python-wheels-with-fortran-for-windows
    - {{ compiler('m2w64_fortran') }}   # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - setuptools
    - cython
    - pybind11
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  # this section will execute run_test.py
  requires:
    - pytest
    - pytest-xdist
    - mpmath
    # make sure we test with all blas implementations
    - blas =*={{ blas_impl }}

about:
  home: http://www.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - rgommers
    - ocefpaf
