build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
test_on_native_only: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
conda_build:
  pkg_format: '2'
