travis:
  secure:
    BINSTAR_TOKEN: JAzY1Z+fOMMR/1SAuvyVxuX0QOA+cYIoM1yc0rKv1Tsj2elMleKw3bQ7/toDsYv0ZVzKUsI3AoUxNAiwcc2tbwpKAaOEiHwH85OQ1UvR1prTtxbaEIDOU2nLn6QG2lramX/PCYeSkAD3egdciCBpD7tK+IiBt4f30h2byLMai3AaUfNJALGBzkJcTaBow7yWG+u+QEi4OFVQtmwSgKc9CgM2Dq7yTIKTgJbw3qr5QkS2Bt4qozkF33OuepRZbxR7QXl94CMHcJn2qPQIx6cVm/CnvOpz2BOxzCQTgzDK4tZqThzj81LTMBM3AkY39MePCN61pszvN81dAAQd6HWrbs/a8RtOEsba7VAHp2WCgeZR8kd6JF0JTtNo5hTrrOA9zHGUmv6dwHWY00wd2ZJf/QYrmAiacb/lUzvHZbTQYiN9CulBKS+oWN2/ngpXF9sf+cVk4dGscYcBCX2pDVaM9sW7JLepuM06psXl93xFCcgzHoy+3Iv1Xf3mA8fkMpcXhYY+8HNmGuI7uKazB7MQDXjY16tcklFIULbVFnriRMQrR9yBh76ei/ALPnbWc4eaBaPz7BnmDCQyux/UJYxyamDB2vkECkbANh+4Tzhdie2WtGJfwvoHGiQ1EF7yyU11Q+3T0Us6YfkPBFCj5K1iy7AlyCOMYVjfPW93rBw2UWI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
