appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wTJ9vxR5vcp4wnsHFGDLdWMPYk8loSpqM0/xat1by0NzDu6X2Dgpe16WlywRXCTh2ROj6FDNxrCSyzrGRCrU+OK13GIG/Ad6+zMVV2fsQpTCfoSVP03NJq3NdNT5ZOuu2r1GMfyM1LKD3+AuU3oBB9URlg5aS1pfujmVZ7ZiSNjZA7EFWsEwN4LSGtJPIclai7TJYAXfGw5G15KXglZmtnZiBf5C0LNdh92nN/TA5YTxsDVpftmXljw7xgIM+AguAXEQT5KIEFZ8wIcl3NF7y/H2gOC6BQsR79SOorl12aEmrMmCYUS0aQl5Mj1b6zKomTC2TwZef/Ol0gskjCHzuS7Uxnuwl4yQ0GVqt13wvTPeN0Y6aps/4Zje3VX9dJc7Zb7GptouB80iiZnQB08zcyzr2uwsVqMHM0ikDcoMB2v93nJimgm7mwUxyUnSwDPJpQy81d7DiWMK3WxDfRzeblJwHAMqnT9sStCIfDwRkNDF1xJ9l9O/9EJIvhEQb6dQ2wuMDsSEEQfe/++L7J/6XfNdQo78/X9GoGWBQKRlAoPngt6X2BKn6FX7wrVTFX7psu5FXbNU8Vhxiy8IXuzs+x9UNEVRv2XyWSHUFKhfbwTQLglD8Lh0JO6rL/it7P1G0wwcF4L5ahruLLRBIQQHHMfeRzBwDbg7s0JYt/oN1Qo=}
conda_forge_output_validation: true
